language: java

jdk:
- oraclejdk8

sudo: true

services:
  - docker

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y openssl docker-ce

before_script:
- ./scripts/generate-ssl-cert.sh

script:
- sudo docker-compose up -d
- mvn clean install

cache:
  directories:
  - $HOME/.m2