version: "3"

services:
  eventstore:
    image: eventstore/eventstore:release-5.0.11
    ports:
    - "7773:7773"
    - "7779:7779"
    - "2113:2113"
    environment:
    - EVENTSTORE_MEM_DB=true
    - EVENTSTORE_RUN_PROJECTIONS=all
    - EVENTSTORE_STATS_PERIOD_SEC=3000
    - EVENTSTORE_EXT_TCP_PORT=7773
    - EVENTSTORE_EXT_SECURE_TCP_PORT=7779
    - EVENTSTORE_CERTIFICATE_FILE=/ssl/domain.p12
    volumes:
    - ./ssl:/ssl
